// Postback Payloads
const POSTBACK_GET_STARTED_PAYLOAD = "get_started"
const POSTBACK_BOOK_APPT_PAYLOAD = "book_appointment"
const POSTBACK_SPEAK_TO_PERSON_PAYLOAD = "speak_to_person"
const POSTBACK_GIVE_PN_PAYLOAD = ""

module.exports = {
  POSTBACK_GET_STARTED_PAYLOAD,
  POSTBACK_BOOK_APPT_PAYLOAD,
  POSTBACK_SPEAK_TO_PERSON_PAYLOAD
}